refactor for optional test completion
justeat/JustEat.RecruitmentTest pull request #37
Opened 2021-03-31 10:20 UTC by marengaz

2021-03-31 11:45 UTC, tabdulradi requested changes

2021-03-31 11:45 UTC, tabdulradi commented on data-and-ai/data-engineer/README.md
> +We would really like you to show off how you code.
```suggestion
```

"show off" might have some bad connotation, also the whole sentence is redundant really.

2021-03-31 11:45 UTC, tabdulradi commented on data-and-ai/data-engineer/README.md
> +At Just Eat we value code that is functional, simple to read and review, demonstrates best practice.
```suggestion
At Just Eat we value code that is functional, simple to read and review, and demonstrates best practice.
```

2021-04-01 12:41 UTC, martincostello commented on data-and-ai/data-engineer/README.md
> +You can complete this assignment in Scala or Python, unless instructed otherwise.
The _"unless"_ suggests to me this is a request, rather than a suggestion.

```suggestion
You should complete this assignment in Scala or Python, unless instructed otherwise. 
```

2021-04-01 12:41 UTC, martincostello commented on data-and-ai/data-engineer/README.md
> +- Make sure you know how the code works, it compiles and you know how to run it with different args
```suggestion
- Make sure you know how the code works, it compiles and you know how to run it with different arguments
```

2021-04-01 12:42 UTC, merged